# Generated by Django 4.2.6 on 2023-10-20 13:51

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Ler mais...', verbose_name='resumo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='titulo'),
        ),
    ]
