# Generated by Django 4.2.6 on 2023-10-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_alter_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_resumo',
            field=models.ImageField(default='Image não encontrada', upload_to='imagens-resumo/', verbose_name='imagem_resumo'),
            preserve_default=False,
        ),
    ]
