# Generated by Django 4.2.6 on 2023-10-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0005_post_imagem_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_resumo',
            field=models.ImageField(upload_to='imagens/', verbose_name='imagem_resumo'),
        ),
    ]
