# Generated by Django 4.2.6 on 2023-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_resumo',
            field=models.ImageField(null=True, upload_to='imagens/', verbose_name='imagem_resumo'),
        ),
    ]
